"use client";
import React, { useState, useEffect, Suspense } from "react";
import { config } from "@fortawesome/fontawesome-svg-core";
import { Provider } from "react-redux";
import { NextUIProvider } from "@nextui-org/react";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Head from "next/head";
import LoaderSuspense from "./Utils/Loader/LoaderSuspense";
import "./globals.css";
import FooterCom from "./CompUtils/Footer/FooterCom";
import Banner from "./CompUtils/Banner";
import Navbarcom from "./CompUtils/Header/Header";
import Specification from "./specification/Specification";
import DataProviderContext from "./DataProviderContext/DataProviderContext";
import { DataContaxt } from "./DataProviderContext/DataProviderContext";
import { DataProvideBYHook } from "./DataProviderContext/DataProviderContext";
import Store from "../app/Redux/Store"; // Update the path as needed
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  gql,
} from "@apollo/client";

const client = new ApolloClient({
  uri: `${process.env.GRAPHQL_SERVER}`,
  cache: new InMemoryCache(),
});

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const RootLayout = ({ children }) => {
  return (
    <>
      <html lang="en">
        <Head>
          {/* Title */}
          <title>
            SoilBooster.in | Soil Booster Technology - Improve Soil Health
          </title>

          {/* Description */}
          <meta
            name="description"
            content="Soil Booster Technology specializes in improving soil health and crop yield. Our innovative solutions enhance agricultural productivity. Visit SoilBooster.in to learn more."
          />

          {/* Keywords */}
          <meta
            name="keywords"
            content="Soil Booster Technology, Soil Health, Crop Yield, Agricultural Productivity, SoilBooster.in"
          />

          {/* Author */}
          <meta
            name="Mr.Guruprasad Revgade"
            content="Soil Booster Technology"
          />

          {/* Viewport */}
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          />
        </Head>
        <body className={inter.className}>
          <NextUIProvider>
            <ApolloProvider client={client}>
              <Provider store={Store}>
                <DataProviderContext>
                  <Suspense fallback={<LoaderSuspense />}>
                    <Banner />
                    <Navbarcom />
                    {children}
                    <Specification />
                    <FooterCom />
                  </Suspense>
                </DataProviderContext>
              </Provider>
            </ApolloProvider>
          </NextUIProvider>
        </body>
      </html>
    </>
  );
};

export default RootLayout;
