"use client";
import React, { useState, useEffect, Suspense } from "react";
import { config } from "@fortawesome/fontawesome-svg-core";
import { Provider } from "react-redux";
import {
  useRouter,
  useSelectedLayoutSegment,
  usePathname,
} from "next/navigation";
import { NextUIProvider } from "@nextui-org/react";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import LoaderSuspense from "./Utils/Loader/LoaderSuspense";
import "./globals.css";
import FooterCom from "./CompUtils/Footer/FooterCom";
import Banner from "./CompUtils/Banner";
import Navbarcom from "./CompUtils/Header/Header";
import Specification from "./specification/Specification";
import DataProviderContext from "./DataProviderContext/DataProviderContext";
import { DataContaxt } from "./DataProviderContext/DataProviderContext";
import { DataProvideBYHook } from "./DataProviderContext/DataProviderContext";
import Store from "../app/Redux/Store"; // Update the path as needed

import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  gql,
} from "@apollo/client";

const client = new ApolloClient({
  uri: `${process.env.GRAPHQL_SERVER}`,
  cache: new InMemoryCache(),
});


config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <NextUIProvider>
            <ApolloProvider client={client}>
              <Provider store={Store}>
                <DataProviderContext>
                  <Suspense fallback={<LoaderSuspense />}>
                    <Banner />
                    <Navbarcom />
                    {children}
                    <Specification />
                    <FooterCom />
                  </Suspense>
                </DataProviderContext>
              </Provider>
            </ApolloProvider>
          </NextUIProvider>
        </body>
      </html>
    </>
  );
};

export default RootLayout;
